question_data = [{"type": "boolean",
                  "difficulty": "medium",
                  "category": "Geography",
                  "question": "There exists an island named Java.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science &amp; Nature",
                  "question": "Sound can travel through a vacuum.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Geography",
                  "question": "The Sonoran Desert is located in eastern Africa.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "History",
                  "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Board Games",
                  "question": "The card game &quot;Munchkin&quot; won the 2001 Origins Award for Best Traditional Card Game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "General Knowledge",
                  "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Sports",
                  "question": "Tennis was once known as Racquetball.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Entertainment: Music",
                  "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium",
                  "category": "Science: Computers",
                  "question": "The HTML5 standard was published in 2014.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy",
                  "category": "Entertainment: Television",
                  "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
